<?php
/**
 * This is the main configuration file for SimpleSAMLphp.
 *
 * @package SimpleSAMLphp
 */

$config = array(
	'admin'            => array(
		'core:AdminPassword',
	),

	'example-userpass' => array(
		'exampleauth:UserPass',

		'users' => array(
			'bio_prof:bio_prof' => array(
				'uid'                    => array( 'bio_prof' ),
				'cwlLoginName'           => array( 'bio_prof' ),
				'cwlLoginKey'            => array( '23456789' ),
				'ubcEduCwlPuid'          => array( '23456789' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'bio_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'bio_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4520001' ),
				'givenName'              => array( 'Bianca' ),
				'sn'                     => array( 'Professor' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID234567890' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'bio_prof2:bio_prof2' => array(
				'uid'                    => array( 'bio_prof2' ),
				'cwlLoginName'           => array( 'bio_prof2' ),
				'cwlLoginKey'            => array( '45678901' ),
				'ubcEduCwlPuid'          => array( '45678901' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'bio_prof2@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'bio_prof2@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4520002' ),
				'givenName'              => array( 'Bernard' ),
				'sn'                     => array( 'Professor' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID456789012' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'bio_student:bio_student' => array(
				'uid'                    => array( 'bio_student' ),
				'cwlLoginName'           => array( 'bio_student' ),
				'cwlLoginKey'            => array( '34567890' ),
				'ubcEduCwlPuid'          => array( '34567890' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'bio_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'bio_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53210001' ),
				'givenName'              => array( 'Bruno' ),
				'sn'                     => array( 'Student' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID345678901' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'bio_student2:bio_student2' => array(
				'uid'                    => array( 'bio_student2' ),
				'cwlLoginName'           => array( 'bio_student2' ),
				'cwlLoginKey'            => array( '56789012' ),
				'ubcEduCwlPuid'          => array( '56789012' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'bio_student2@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'bio_student2@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53210002' ),
				'givenName'              => array( 'Beatrice' ),
				'sn'                     => array( 'Student' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID567890123' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'bio_student3:bio_student3' => array(
				'uid'                    => array( 'bio_student3' ),
				'cwlLoginName'           => array( 'bio_student3' ),
				'cwlLoginKey'            => array( '67890123' ),
				'ubcEduCwlPuid'          => array( '67890123' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'bio_student3@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'bio_student3@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53210003' ),
				'givenName'              => array( 'Bennett' ),
				'sn'                     => array( 'Student' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID678901234' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'faculty:faculty' => array(
				'uid'                    => array( 'faculty-user' ),
				'cwlLoginName'           => array( 'faculty-user' ),
				'cwlLoginKey'            => array( '12345678' ),
				'ubcEduCwlPuid'          => array( '12345678' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'faculty@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'faculty-user@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4520000' ),
				'givenName'              => array( 'John' ),
				'sn'                     => array( 'Faculty' ),
				'eduPersonTargetedId'    => array( 'http://localhost:6122!https://your-app!ID123456789' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'student:student' => array(
				'uid'                    => array( 'student-user' ),
				'cwlLoginName'           => array( 'student-user' ),
				'cwlLoginKey'            => array( '87654321' ),
				'ubcEduCwlPuid'          => array( '87654321' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'student@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'student-user@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '12345678' ),
				'givenName'              => array( 'Jane' ),
				'sn'                     => array( 'Student' ),
				'eduPersonTargetedId'    => array( 'http://localhost:6122!https://your-app!ID987654321' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'staff:staff'     => array(
				'uid'                    => array( 'staff-user' ),
				'cwlLoginName'           => array( 'staff-user' ),
				'cwlLoginKey'            => array( '11223344' ),
				'ubcEduCwlPuid'          => array( '11223344' ),
				'eduPersonAffiliation'   => array( 'staff' ),
				'mail'                   => array( 'staff@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'staff-user@ubc.ca' ),
				'employeeNumber'         => array( '99887766' ),
				'givenName'              => array( 'Staff' ),
				'sn'                     => array( 'Member' ),
				'eduPersonTargetedId'    => array( 'http://localhost:6122!https://your-app!ID11223344' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'staff_advisor:staff_advisor' => array(
				'uid'                    => array( 'staff_advisor' ),
				'cwlLoginName'           => array( 'staff_advisor' ),
				'cwlLoginKey'            => array( '43000001' ),
				'ubcEduCwlPuid'          => array( '43000001' ),
				'eduPersonAffiliation'   => array( 'staff' ),
				'mail'                   => array( 'staff_advisor@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'staff_advisor@ubc.ca' ),
				'employeeNumber'         => array( '4550001' ),
				'givenName'              => array( 'Amara' ),
				'sn'                     => array( 'Okafor' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID43000001' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			'staff_researcher:staff_researcher' => array(
				'uid'                    => array( 'staff_researcher' ),
				'cwlLoginName'           => array( 'staff_researcher' ),
				'cwlLoginKey'            => array( '43000002' ),
				'ubcEduCwlPuid'          => array( '43000002' ),
				'eduPersonAffiliation'   => array( 'staff' ),
				'mail'                   => array( 'staff_researcher@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'staff_researcher@ubc.ca' ),
				'employeeNumber'         => array( '4550002' ),
				'givenName'              => array( 'Theo' ),
				'sn'                     => array( 'Martin' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID43000002' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// =================================================================
			// EXTRA PERSONAS — broader account spread for manual testing.
			// PUID (cwlLoginKey/ubcEduCwlPuid) + employeeNumber/studentNumber
			// match the academic_api_fake seed (src/seed.ts) one-for-one, so
			// login -> academic-API lookups line up end to end.
			// password == login for every account below.
			// =================================================================

			// ---- Extra instructors (faculty) -------------------------------
			// cpsc_prof — CPSC 121, co-teaches CPSC 210.
			'cpsc_prof:cpsc_prof' => array(
				'uid'                    => array( 'cpsc_prof' ),
				'cwlLoginName'           => array( 'cpsc_prof' ),
				'cwlLoginKey'            => array( '41000001' ),
				'ubcEduCwlPuid'          => array( '41000001' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'cpsc_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'cpsc_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530001' ),
				'givenName'              => array( 'Felix' ),
				'sn'                     => array( 'Ramos' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000001' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// cpsc_prof2 — co-teaches CPSC 210, owns CPSC 221 next term.
			'cpsc_prof2:cpsc_prof2' => array(
				'uid'                    => array( 'cpsc_prof2' ),
				'cwlLoginName'           => array( 'cpsc_prof2' ),
				'cwlLoginKey'            => array( '41000002' ),
				'ubcEduCwlPuid'          => array( '41000002' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'cpsc_prof2@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'cpsc_prof2@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530002' ),
				'givenName'              => array( 'Greta' ),
				'sn'                     => array( 'Lindqvist' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000002' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// empty_prof — teaches NOTHING (empty onboarding picker).
			'empty_prof:empty_prof' => array(
				'uid'                    => array( 'empty_prof' ),
				'cwlLoginName'           => array( 'empty_prof' ),
				'cwlLoginKey'            => array( '41000003' ),
				'ubcEduCwlPuid'          => array( '41000003' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'empty_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'empty_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530003' ),
				'givenName'              => array( 'Harold' ),
				'sn'                     => array( 'Nkemelu' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000003' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// cancel_prof — only owns a Canceled section (CPSC 313).
			'cancel_prof:cancel_prof' => array(
				'uid'                    => array( 'cancel_prof' ),
				'cwlLoginName'           => array( 'cancel_prof' ),
				'cwlLoginKey'            => array( '41000004' ),
				'ubcEduCwlPuid'          => array( '41000004' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'cancel_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'cancel_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530004' ),
				'givenName'              => array( 'Ingrid' ),
				'sn'                     => array( 'Sorensen' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000004' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// mega_prof — the huge CPSC 100 lecture (>500 roster).
			'mega_prof:mega_prof' => array(
				'uid'                    => array( 'mega_prof' ),
				'cwlLoginName'           => array( 'mega_prof' ),
				'cwlLoginKey'            => array( '41000005' ),
				'ubcEduCwlPuid'          => array( '41000005' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'mega_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'mega_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530005' ),
				'givenName'              => array( 'Julius' ),
				'sn'                     => array( 'Adeyemi' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000005' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// waitlist_prof — owns a Waitlist (MATH 152) + a Closed (MATH 221) section.
			'waitlist_prof:waitlist_prof' => array(
				'uid'                    => array( 'waitlist_prof' ),
				'cwlLoginName'           => array( 'waitlist_prof' ),
				'cwlLoginKey'            => array( '41000006' ),
				'ubcEduCwlPuid'          => array( '41000006' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'waitlist_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'waitlist_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530006' ),
				'givenName'              => array( 'Karina' ),
				'sn'                     => array( 'Volkov' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000006' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// personal_prof — Personal email only on the academic-API record (ENGL 220).
			'personal_prof:personal_prof' => array(
				'uid'                    => array( 'personal_prof' ),
				'cwlLoginName'           => array( 'personal_prof' ),
				'cwlLoginKey'            => array( '41000007' ),
				'ubcEduCwlPuid'          => array( '41000007' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'personal_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'personal_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530007' ),
				'givenName'              => array( 'Mira' ),
				'sn'                     => array( 'Dvorak' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000007' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// legal_prof — Legal name only (no Preferred Name) on the academic-API record (ENGL 301).
			'legal_prof:legal_prof' => array(
				'uid'                    => array( 'legal_prof' ),
				'cwlLoginName'           => array( 'legal_prof' ),
				'cwlLoginKey'            => array( '41000008' ),
				'ubcEduCwlPuid'          => array( '41000008' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'legal_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'legal_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530008' ),
				'givenName'              => array( 'Nadia' ),
				'sn'                     => array( 'OBrien' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000008' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// merge_prof — identity merge in progress (MATH 215).
			'merge_prof:merge_prof' => array(
				'uid'                    => array( 'merge_prof' ),
				'cwlLoginName'           => array( 'merge_prof' ),
				'cwlLoginKey'            => array( '41000009' ),
				'ubcEduCwlPuid'          => array( '41000009' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'merge_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'merge_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530009' ),
				'givenName'              => array( 'Oscar' ),
				'sn'                     => array( 'Pavlenko' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000009' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// dual_prof — dual identity: BOTH employeeNumber and studentNumber (BIOC 449).
			'dual_prof:dual_prof' => array(
				'uid'                    => array( 'dual_prof' ),
				'cwlLoginName'           => array( 'dual_prof' ),
				'cwlLoginKey'            => array( '41000010' ),
				'ubcEduCwlPuid'          => array( '41000010' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'dual_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'dual_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530010' ),
				'studentNumber'          => array( '53320001' ),
				'givenName'              => array( 'Petra' ),
				'sn'                     => array( 'Castellanos' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000010' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// crossterm_prof — teaches CPSC 320 in BOTH terms.
			'crossterm_prof:crossterm_prof' => array(
				'uid'                    => array( 'crossterm_prof' ),
				'cwlLoginName'           => array( 'crossterm_prof' ),
				'cwlLoginKey'            => array( '41000011' ),
				'ubcEduCwlPuid'          => array( '41000011' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'crossterm_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'crossterm_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530011' ),
				'givenName'              => array( 'Quincy' ),
				'sn'                     => array( 'Abara' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000011' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// arts_prof — a second Arts (ENGL) instructor (ENGL 222).
			'arts_prof:arts_prof' => array(
				'uid'                    => array( 'arts_prof' ),
				'cwlLoginName'           => array( 'arts_prof' ),
				'cwlLoginKey'            => array( '41000012' ),
				'ubcEduCwlPuid'          => array( '41000012' ),
				'eduPersonAffiliation'   => array( 'faculty' ),
				'mail'                   => array( 'arts_prof@ubc.ca' ),
				'eduPersonPrincipalName' => array( 'arts_prof@ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'employeeNumber'         => array( '4530012' ),
				'givenName'              => array( 'Rosa' ),
				'sn'                     => array( 'Beaumont' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID41000012' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// ---- Extra students --------------------------------------------
			// cpsc_student — clean happy path (CPSC 121).
			'cpsc_student:cpsc_student' => array(
				'uid'                    => array( 'cpsc_student' ),
				'cwlLoginName'           => array( 'cpsc_student' ),
				'cwlLoginKey'            => array( '42000001' ),
				'ubcEduCwlPuid'          => array( '42000001' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'cpsc_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'cpsc_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310001' ),
				'givenName'              => array( 'Aiko' ),
				'sn'                     => array( 'Tanaka' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000001' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// conflict_student — CONFLICT: two sections in the same term.
			'conflict_student:conflict_student' => array(
				'uid'                    => array( 'conflict_student' ),
				'cwlLoginName'           => array( 'conflict_student' ),
				'cwlLoginKey'            => array( '42000002' ),
				'ubcEduCwlPuid'          => array( '42000002' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'conflict_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'conflict_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310002' ),
				'givenName'              => array( 'Bjorn' ),
				'sn'                     => array( 'Eriksson' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000002' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// empty_student — enrolled in NOTHING.
			'empty_student:empty_student' => array(
				'uid'                    => array( 'empty_student' ),
				'cwlLoginName'           => array( 'empty_student' ),
				'cwlLoginKey'            => array( '42000003' ),
				'ubcEduCwlPuid'          => array( '42000003' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'empty_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'empty_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310003' ),
				'givenName'              => array( 'Chloe' ),
				'sn'                     => array( 'Mbeki' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000003' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// cancel_student — only enrollment is a Canceled section (CPSC 313).
			'cancel_student:cancel_student' => array(
				'uid'                    => array( 'cancel_student' ),
				'cwlLoginName'           => array( 'cancel_student' ),
				'cwlLoginKey'            => array( '42000004' ),
				'ubcEduCwlPuid'          => array( '42000004' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'cancel_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'cancel_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310004' ),
				'givenName'              => array( 'Diego' ),
				'sn'                     => array( 'Ferreira' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000004' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// waitlist_student — sole enrollment is a Waitlist section (MATH 152).
			'waitlist_student:waitlist_student' => array(
				'uid'                    => array( 'waitlist_student' ),
				'cwlLoginName'           => array( 'waitlist_student' ),
				'cwlLoginKey'            => array( '42000005' ),
				'ubcEduCwlPuid'          => array( '42000005' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'waitlist_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'waitlist_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310005' ),
				'givenName'              => array( 'Elina' ),
				'sn'                     => array( 'Korhonen' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000005' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// personal_student — Personal email only on the academic-API record (CPSC 210).
			'personal_student:personal_student' => array(
				'uid'                    => array( 'personal_student' ),
				'cwlLoginName'           => array( 'personal_student' ),
				'cwlLoginKey'            => array( '42000006' ),
				'ubcEduCwlPuid'          => array( '42000006' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'personal_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'personal_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310006' ),
				'givenName'              => array( 'Farid' ),
				'sn'                     => array( 'Nasser' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000006' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// noemail_student — NO email on the academic-API record (ENGL 220).
			'noemail_student:noemail_student' => array(
				'uid'                    => array( 'noemail_student' ),
				'cwlLoginName'           => array( 'noemail_student' ),
				'cwlLoginKey'            => array( '42000007' ),
				'ubcEduCwlPuid'          => array( '42000007' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'noemail_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'noemail_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310007' ),
				'givenName'              => array( 'Gabriela' ),
				'sn'                     => array( 'Rossi' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000007' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// legal_student — Legal name only (no Preferred Name) on the academic-API record (ENGL 301).
			'legal_student:legal_student' => array(
				'uid'                    => array( 'legal_student' ),
				'cwlLoginName'           => array( 'legal_student' ),
				'cwlLoginKey'            => array( '42000008' ),
				'ubcEduCwlPuid'          => array( '42000008' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'legal_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'legal_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310008' ),
				'givenName'              => array( 'Hassan' ),
				'sn'                     => array( 'Bakr' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000008' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// merge_student — identity merge in progress (MATH 215).
			'merge_student:merge_student' => array(
				'uid'                    => array( 'merge_student' ),
				'cwlLoginName'           => array( 'merge_student' ),
				'cwlLoginKey'            => array( '42000009' ),
				'ubcEduCwlPuid'          => array( '42000009' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'merge_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'merge_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310009' ),
				'givenName'              => array( 'Ines' ),
				'sn'                     => array( 'Delacroix' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000009' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// ta_student — dual identity: BOTH studentNumber and employeeNumber (CPSC 210, BIOC 449).
			'ta_student:ta_student' => array(
				'uid'                    => array( 'ta_student' ),
				'cwlLoginName'           => array( 'ta_student' ),
				'cwlLoginKey'            => array( '42000010' ),
				'ubcEduCwlPuid'          => array( '42000010' ),
				'eduPersonAffiliation'   => array( 'student', 'staff' ),
				'mail'                   => array( 'ta_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'ta_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310010' ),
				'employeeNumber'         => array( '4540001' ),
				'givenName'              => array( 'Jonas' ),
				'sn'                     => array( 'Weber' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000010' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// ta_student2 — second TA with both student and staff associations.
			'ta_student2:ta_student2' => array(
				'uid'                    => array( 'ta_student2' ),
				'cwlLoginName'           => array( 'ta_student2' ),
				'cwlLoginKey'            => array( '42000013' ),
				'ubcEduCwlPuid'          => array( '42000013' ),
				'eduPersonAffiliation'   => array( 'student', 'staff' ),
				'mail'                   => array( 'ta_student2@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'ta_student2@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310013' ),
				'employeeNumber'         => array( '4540002' ),
				'givenName'              => array( 'Mei' ),
				'sn'                     => array( 'Santos' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000013' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// mega_student — sits in the huge CPSC 100 roster.
			'mega_student:mega_student' => array(
				'uid'                    => array( 'mega_student' ),
				'cwlLoginName'           => array( 'mega_student' ),
				'cwlLoginKey'            => array( '42000011' ),
				'ubcEduCwlPuid'          => array( '42000011' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'mega_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'mega_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310011' ),
				'givenName'              => array( 'Kenji' ),
				'sn'                     => array( 'Yamamoto' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000011' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),

			// multi_student — spans BOTH terms across several sections.
			'multi_student:multi_student' => array(
				'uid'                    => array( 'multi_student' ),
				'cwlLoginName'           => array( 'multi_student' ),
				'cwlLoginKey'            => array( '42000012' ),
				'ubcEduCwlPuid'          => array( '42000012' ),
				'eduPersonAffiliation'   => array( 'student' ),
				'mail'                   => array( 'multi_student@student.ubc.ca' ),
				'eduPersonPrincipalName' => array( 'multi_student@student.ubc.ca' ),
				'eduPersonEntitlement'   => array( 'urn:mace:ubc.ca:library' ),
				'studentNumber'          => array( '53310012' ),
				'givenName'              => array( 'Lucia' ),
				'sn'                     => array( 'Moreno' ),
				'eduPersonTargetedId'    => array( 'http://localhost:8080!https://your-app!ID42000012' ),
				'isMemberOf'             => array( 'Services:Email:User' ),
			),
		),
	),
);
